POST http://localhost:5001/los-santos-tourist-guide/us-central1/api/createDatabase HTTP/1.1
Content-Type: application/json

{
  "users": [{
    "name": "Erick Vieira",
    "email": "erick-vieira-s@outlook.com",
    "profilePicture": "uma foto bem bacana"
  }, {
    "name": "Erick Vieira",
    "email": "erick-vieira-s@outlook.com",
    "profilePicture": "uma foto bem bacana"
  }],
  "touristspots": [{
    "name": "Maze Bank",
    "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum repellat iure eligendi autem impedit corrupti fugiat repudiandae incidunt, aspernatur dignissimos totam deleniti eaque qui ab eveniet beatae obcaecati asperiores enim!",
    "adjacentStreets": ["Groove Street", "Lincoln Avenue"],
    "icon": "none",
    "ticketPrice": "free",
    "allowsPhotography": true,
    "hasMetalDetector": true,
    "categories": [ "business" ],
    "businessHours": [{ "day": "sun", "opensAt": "08:00", "closesAt": "19:00" }],
    "coordinates": { "lat": 33.738177, "lng": -118.813650 }
  }, {
    "name": "Maze Bank",
    "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum repellat iure eligendi autem impedit corrupti fugiat repudiandae incidunt, aspernatur dignissimos totam deleniti eaque qui ab eveniet beatae obcaecati asperiores enim!",
    "adjacentStreets": ["Groove Street", "Lincoln Avenue"],
    "icon": "none",
    "ticketPrice": "free",
    "allowsPhotography": true,
    "hasMetalDetector": true,
    "categories": [ "business" ],
    "businessHours": [{ "day": "sun", "opensAt": "08:00", "closesAt": "19:00" }],
    "coordinates": { "lat": 33.738177, "lng": -118.813650 }
  }]
}

GET https://us-central1-los-santos-tourist-guide.cloudfunctions.net/api/spot/ HTTP/1.1
